### ISSUE TITLE
Support serialize only DTO

### ISSUE THREAD

**Issue by davydov-a** [eraga/kotlin-data-tools#17]
Sometimes need to generate DTO, which is going to be used only for rendering. 
There is no need to generate `updateBy` method. 
Also, if DTO have property with same name, but another class, code will not be compiled, due to mismatch classes.

**Comment by tntclaus** [comment]
> There is no need to generate updateBy method.

What's wrong with excess `updateBy` method?

> DTO have property with same name

Why is it required for DTO to have field of same name with Immutable entity but with different class?

**Comment by davydov-a** [comment]
> Why is it required for DTO to have field of same name with Immutable entity but with different class?

The same name required to save context, but it may have custom fields and is able to be created only via another services.

> What's wrong with excess updateBy method?

As I told early, there is no need to generate `updateBy` method, when we know, that DTO is going to be used just for rendering.

**Comment by tntclaus** [comment]
> The same name required to save context

Is `DTO.someFieldName` somehow related to `Immutable.someFieldName` or are they completely distinct? If they are not distinct, maybe they can be somehow transformed to one another? Code example will be handy here. 

> there is no need to generate updateBy method

That's obvious and still doesn't answer my question: what's wrong with excess updateBy method? Does it prevent you from doing something?

**Comment by davydov-a** [comment]
There is wrong using of generator. I'm going to declare another DTO class without any generation and create it via service.
