### ISSUE TITLE
Support defining fields in the main constructor

### ISSUE THREAD

**Issue by davydov-a** [eraga/kotlin-data-tools#9]
Current implementation does not allow define fields in the main constructor to allow default value. 

Defining fields int the main constructor is important for hibernate to avoid creating of empty nested entities.

**Comment by tntclaus** [comment]
`Implement.NoInit` tells processor to not init property with default value and use constructor instead

```
@Implement.Immutable
abstract class MeModel() {
    @Implement.NoInit
    abstract var a: String
```

will produce

```
public final class ImmutableMe(
  public override var a: String
) : MeModel()
```
